-- supabase_timetable_reset.sql
-- Resets all timetable_slots to values from "Timetable odd semester 26-27" Excel.
-- Run ONCE in Supabase SQL Editor to create/replace the function.
-- App calls it via: supabase.rpc('reset_timetable_slots')
-- Does NOT delete rows — only upserts the 186 slots that appear in the Excel.

CREATE OR REPLACE FUNCTION reset_timetable_slots()
RETURNS void
LANGUAGE sql
SECURITY DEFINER
AS $func$
  INSERT INTO timetable_slots
    (class_name, day, period_name, course_code, course_name, faculty_name, batch_details, is_elective)
  VALUES
  ('1BcomIBA', 'MON', 'M1', 'BIBA104-1', 'Legal Aspects of Business', 'CS Monika Agarwal', NULL, false),
  ('1BcomIBA', 'MON', 'M2', 'BIBA102-1', 'Business Mathematics and Statistics', 'Dr. Bhagyalakshmi', NULL, false),
  ('1BcomIBA', 'MON', 'P3', 'BIBA104-1', 'Legal Aspects of Business', 'CS Monika Agarwal', NULL, false),
  ('1BcomIBA', 'TUE', 'M1', 'BIBA101-1', 'Foundations of Accounting', 'Dr. Shruthi Joshi', NULL, false),
  ('1BcomIBA', 'TUE', 'M2', 'BIBA102-1', 'Business Mathematics and Statistics', 'Dr. Bhagyalakshmi', NULL, false),
  ('1BcomIBA', 'TUE', 'P3', 'BIBA103-1', 'Busi.Economics', 'Dr. Ravi', NULL, false),
  ('1BcomIBA', 'WED', 'M1', 'BIBA101-1', 'Foundations of Accounting', 'Dr. Shruthi Joshi', NULL, false),
  ('1BcomF&A', 'MON', 'M1', 'COC103-1', 'Business Mathematics and Statistics', 'Dr. Bhagyalakshmi', NULL, false),
  ('1BcomF&A', 'MON', 'M2', 'COC101-1', 'Fundamentals of accounting', 'Dr. Ravi', NULL, false),
  ('1BcomF&A', 'MON', 'P3', 'COC102-1', 'Business economics', NULL, NULL, false),
  ('1BcomF&A', 'TUE', 'M1', 'COC161-1', 'Legal Aspects of Business', 'CS Monika Agarwal', NULL, false),
  ('1BcomF&A', 'TUE', 'M2', 'COC161-1', 'Legal Aspects of Business', 'CS Monika Agarwal', NULL, false),
  ('1BcomF&A', 'WED', 'M1', 'COC103-1', 'Business Mathematics and Statistics', 'Dr. Bhagyalakshmi', NULL, false),
  ('1BcomIAF', 'MON', 'M1', 'BIAF103-1', 'Principles of Management and Organisational Behaviour', 'Prof. Bharath / Prof. Shreshta', NULL, true),
  ('1BcomIAF', 'TUE', 'M1', 'BIAF103-1', 'Principles of Management and Organisational Behaviour', 'Prof. Bharath / Prof. Shreshta', NULL, true),
  ('1BcomIAF', 'TUE', 'M2', 'BIAF103-1', 'Principles of Management and Organisational Behaviour', 'Prof. Bharath / Prof. Shreshta', NULL, true),
  ('1BcomIAF', 'TUE', 'P3', 'DPS161B - 1', 'Fundamentals of Risk and Insurance Skilling / Business Communication and Workplace Skills', 'Dr. Shruthi Joshi', NULL, false),
  ('1BcomIAF', 'WED', 'M1', 'BIAF101-1', 'Financial Accounting', 'Dr. Narasimha Murthy', NULL, false),
  ('1BcomIAF', 'WED', 'M2', 'BIAF101-1', 'Organisational Study', 'Dr. Thirupathi', NULL, false),
  ('3BcomIBA', 'MON', 'M1', 'BIBA302-3', 'Business Finance', 'Dr. Hridhya', NULL, false),
  ('3BcomIBA', 'MON', 'M2', 'BIBA261-3', 'Corporate Law', 'Dr. Deon Babloo Thomas', NULL, false),
  ('3BcomIBA', 'MON', 'P2', 'BIBA301-3', 'Management Accounting', 'Dr. Ravi', NULL, false),
  ('3BcomIBA', 'TUE', 'M1', 'BIBA302-3', 'Business Finance', 'Dr. Hridhya', NULL, false),
  ('3BcomIBA', 'TUE', 'M2', 'BIBA202-3', 'Financial Accounting and Reporting – II', 'CA Sangharsh', NULL, false),
  ('3BcomIBA', 'TUE', 'P1', 'BIBA301-3', 'Management Accounting', 'Dr. Ravi', NULL, false),
  ('3BcomIBA', 'WED', 'M1', 'BIBA303-3', 'Corporate Reporting', 'CA Abhay', NULL, false),
  ('3BcomIBA', 'WED', 'M2', 'BIBA202-3', 'Financial Accounting and Reporting – II', 'CA Sangharsh', NULL, false),
  ('3BcomIBA', 'WED', 'P2', 'BIBA301-3', 'Management Accounting', 'Dr. Ravi', NULL, false),
  ('3BcomF&A(A)', 'MON', 'M1', 'COC201-3', 'Financial Accounting and Reporting – II', 'CA Sangharsh', NULL, false),
  ('3BcomF&A(A)', 'MON', 'M2', 'COC201-3', 'Financial Accounting and Reporting – II', 'CA Sangharsh', NULL, false),
  ('3BcomF&A(A)', 'MON', 'P2', 'COC361- 3', 'Corporate Legal Framework II', 'Dr. Deon Babloo Thomas', NULL, false),
  ('3BcomF&A(A)', 'TUE', 'M1', 'COC201-3', 'Financial Accounting and Reporting – II', 'CA Sangharsh', NULL, false),
  ('3BcomF&A(A)', 'TUE', 'M2', 'COC203-3', 'Financial Management 1', 'Dr. Thirupathi', NULL, false),
  ('3BcomF&A(A)', 'TUE', 'P1', 'COC361- 3', 'Corporate Legal Framework II', 'Dr. Deon Babloo Thomas', NULL, false),
  ('3BcomF&A(A)', 'WED', 'M1', 'COC301-3', 'Management Accounting', 'Dr. Ravi', NULL, false),
  ('3BcomF&A(A)', 'WED', 'M2', 'COC301-3', 'Management Accounting', 'Dr. Ravi', NULL, false),
  ('3BcomF&A(A)', 'WED', 'P2', 'COC203-3', 'Financial Management 1', 'Dr. Thirupathi', NULL, false),
  ('3BcomF&A(B)', 'MON', 'M1', 'COC361- 3', 'CORPORATE LEGAL FRAMEWORK - II', 'Dr. Deon Babloo Thomas', NULL, false),
  ('3BcomF&A(B)', 'MON', 'P2', 'COC301-3', 'Management accounting', 'Dr. Kantharaju', NULL, false),
  ('3BcomF&A(B)', 'TUE', 'M1', 'COC361- 3', 'CORPORATE LEGAL FRAMEWORK - II', 'Dr. Deon Babloo Thomas', NULL, false),
  ('3BcomF&A(B)', 'TUE', 'M2', 'COC203-3', 'Financial Management', 'Dr. Shruthi Joshi', NULL, false),
  ('3BcomF&A(B)', 'TUE', 'P1', NULL, 'Auditing 1', 'Dr. Thirupathi', NULL, false),
  ('3BcomF&A(B)', 'WED', 'M1', 'COC201-3', 'Financial Accounting and Reporting – II', 'CA Sangharsh', NULL, false),
  ('3BcomF&A(B)', 'WED', 'M2', 'COC301-3', 'Management accounting', 'Dr. Kantharaju', NULL, false),
  ('3BcomF&A(B)', 'WED', 'P2', 'COC203-3', 'Financial Management', 'Dr. Shruthi Joshi', NULL, false),
  ('3BcomIAF', 'MON', 'M1', 'BIAF203-3', 'Business & Corporate Law', 'Dr. Narasimha Murthy', NULL, false),
  ('3BcomIAF', 'MON', 'M2', 'DPS161-3', 'Entrepreneurship', 'Prof. Bharath / Prof. Shreshta', NULL, true),
  ('3BcomIAF', 'MON', 'P1', 'DPS161-3', 'Entrepreneurship', 'Prof. Bharath / Prof. Shreshta', NULL, true),
  ('3BcomIAF', 'MON', 'P2', 'BIAF204-3', 'Financial Management', 'Dr. Shruthi Joshi', NULL, false),
  ('3BcomIAF', 'TUE', 'M1', 'BIAF202 - 3', 'Financial Reporting', 'Bhoomika Urs ACCA', NULL, false),
  ('3BcomIAF', 'TUE', 'M2', 'BIAF201-3', 'Cost Accounting', 'Dr. Kantharaju', NULL, false),
  ('3BcomIAF', 'TUE', 'P1', 'DPS161-3', 'Entrepreneurship', 'Prof. Bharath / Prof. Shreshta', NULL, true),
  ('3BcomIAF', 'WED', 'M1', 'BIAF201-3', 'Cost Accounting', 'Dr. Kantharaju', NULL, false),
  ('3BcomIAF', 'WED', 'M2', 'BIAF202 - 3', 'Financial Reporting', 'Bhoomika Urs ACCA', NULL, false),
  ('3BcomIAF', 'WED', 'P1', 'BIAF201-3', 'Cost Accounting', 'Dr. Kantharaju', NULL, false),
  ('3BcomIAF', 'WED', 'P2', 'BIAF203-3', 'Business & Corporate Law', 'Dr. Narasimha Murthy', NULL, false),
  ('5BcomF&A(A)', 'MON', 'M1', 'DPS303-5A/ DPS303-5B', 'Corporate reporting/ IAPM', 'CA Abhay / Dr. Diliphan', NULL, true),
  ('5BcomF&A(A)', 'MON', 'M2', 'DPS303-5A/ DPS303-5B', 'Corporate reporting/ IAPM', 'CA Abhay / Dr. Diliphan', NULL, true),
  ('5BcomF&A(A)', 'MON', 'P2', 'COC302-5', 'Entrepreneurship and Start Up Management', 'Prof. Shreshta', NULL, false),
  ('5BcomF&A(A)', 'TUE', 'M1', 'DPS401-5', 'Research Methodology', 'Dr. Thirupathi', NULL, false),
  ('5BcomF&A(A)', 'TUE', 'M2', 'COC301-5', 'Strategic Cost Management', 'Bhoomika Urs ACCA', NULL, false),
  ('5BcomF&A(A)', 'TUE', 'P2', 'COC302-5', 'Entrepreneurship and Start Up Management', 'Prof. Shreshta', NULL, false),
  ('5BcomF&A(A)', 'WED', 'M1', 'COC302-5', 'Entrepreneurship and Start Up Management', 'Prof. Shreshta', NULL, false),
  ('5BcomF&A(A)', 'WED', 'M2', 'COC302-5', 'Entrepreneurship and Start Up Management', 'Prof. Shreshta', NULL, false),
  ('5BcomF&A(A)', 'WED', 'P2', 'COC301-5', 'Strategic Cost Management', 'Bhoomika Urs ACCA', NULL, false),
  ('5BcomF&A(B)', 'MON', 'M1', 'DPS303-5A/ DPS303-5B', 'Corporate reporting/ IAPM', 'CA Abhay / Dr. Diliphan', NULL, true),
  ('5BcomF&A(B)', 'MON', 'M2', 'DPS303-5A/ DPS303-5B', 'Corporate reporting/ IAPM', 'CA Abhay / Dr. Diliphan', NULL, true),
  ('5BcomF&A(B)', 'MON', 'P1', 'COC302-5', 'Entrepreneurship and Start Up Management', 'Dr. Diliphan', NULL, false),
  ('5BcomF&A(B)', 'TUE', 'M1', 'DPS481-5', 'Industry Practicum', 'Dr. Kantharaju', NULL, false),
  ('5BcomF&A(B)', 'TUE', 'M2', 'DPS401-5', 'Research Methodology', 'Dr. Hridhya', NULL, false),
  ('5BcomF&A(B)', 'TUE', 'P1', 'COC302-5', 'Entrepreneurship and Start Up Management', 'Dr. Diliphan', NULL, false),
  ('5BcomF&A(B)', 'WED', 'M1', 'DPS401-5', 'Research Methodology', 'Dr. Hridhya', NULL, false),
  ('5BcomF&A(B)', 'WED', 'M2', 'DPS401-5', 'Research Methodology', 'Dr. Hridhya', NULL, false),
  ('5BcomF&A(B)', 'WED', 'P2', 'COC302-5', 'Entrepreneurship and Start Up Management', 'Dr. Diliphan', NULL, false),
  ('5BcomIAF', 'MON', 'M1', 'BIAF301-5', 'Corporate Reporting', 'Bhoomika Urs ACCA', NULL, false),
  ('5BcomIAF', 'MON', 'M2', 'BIAF302-5', 'Corporate Governance, Risk & Ethics', 'CS Monika Agarwal', NULL, false),
  ('5BcomIAF', 'MON', 'P2', 'BIAF303B-5/ DPS303A-5', 'Entrepreneurial Venture Planning and Communication Strategy / Investment Analysis and Portfolio Management', 'Prof. Bharath / Dr. Diliphan', NULL, true),
  ('5BcomIAF', 'TUE', 'M1', 'BIAF303-5', 'Strategic Business Management', 'Dr. Narasimha Murthy', NULL, false),
  ('5BcomIAF', 'TUE', 'M2', 'BIAF303-5', 'Strategic Business Management', 'Dr. Narasimha Murthy', NULL, false),
  ('5BcomIAF', 'TUE', 'P2', 'BIAF303B-5/ DPS303A-5', 'Entrepreneurial Venture Planning and Communication Strategy / Investment Analysis and Portfolio Management', 'Prof. Bharath / Dr. Diliphan', NULL, true),
  ('5BcomIAF', 'WED', 'M1', 'BIAF301-5', 'Corporate Reporting', 'Bhoomika Urs ACCA', NULL, false),
  ('5BcomIAF', 'WED', 'M2', 'BIAF302-5', 'Corporate Governance, Risk & Ethics', 'CS Monika Agarwal', NULL, false),
  ('5BcomIAF', 'WED', 'P2', 'BIAF302-5', 'Corporate Governance, Risk & Ethics', 'CS Monika Agarwal', NULL, false),
  ('7BcomF&A', 'MON', 'M1', 'DPS405A-7/ COC405B-7', 'BUSINESS ANALYSIS AND VALUATION /IFRS', 'CA Vishal Gupta / CA Rejo', NULL, true),
  ('7BcomF&A', 'MON', 'M2', 'DPS405A-7/ COC405B-7', 'BUSINESS ANALYSIS AND VALUATION /IFRS', 'CA Vishal Gupta / CA Rejo', NULL, true),
  ('7BcomF&A', 'MON', 'P1', 'DPS401-7', 'International Business', 'Dr. Kantharaju', NULL, false),
  ('7BcomF&A', 'TUE', 'M1', 'DPS405A-7/ COC405B-7', 'BUSINESS ANALYSIS AND VALUATION /IFRS', 'CA Vishal Gupta / CA Rejo', NULL, true),
  ('7BcomF&A', 'TUE', 'M2', 'DPS405A-7/ COC405B-7', 'BUSINESS ANALYSIS AND VALUATION /IFRS', 'CA Vishal Gupta / CA Rejo', NULL, true),
  ('7BcomF&A', 'TUE', 'P1', 'DPS401-7', 'International Business', 'Dr. Kantharaju', NULL, false),
  ('7BcomF&A', 'WED', 'M1', 'DPS402-7', 'BUSINESS ANALYTICS – I', 'Dr. Diliphan', NULL, false),
  ('7BcomF&A', 'WED', 'P1', 'DPS402-7', 'BUSINESS ANALYTICS – I', 'Dr. Diliphan', NULL, false),
  ('1BcomIBA', 'THU', 'M1', 'BIBA102-1', 'Business Mathematics and Statistics', 'Dr. Bhagyalakshmi', NULL, false),
  ('1BcomIBA', 'THU', 'M2', 'BIBA162-1', 'organisational Study', 'Bhoomika Urs ACCA', NULL, false),
  ('1BcomIBA', 'THU', 'P1', 'BIBA101-1', 'Foundations of Accounting', 'Dr. Shruthi Joshi', NULL, false),
  ('1BcomIBA', 'THU', 'P2', 'BIBA104-1', 'Legal Aspects of Business', 'CS Monika Agarwal', NULL, false),
  ('1BcomIBA', 'THU', 'P3', NULL, 'PECF', NULL, NULL, false),
  ('1BcomIBA', 'FRI', 'M1', 'BIBA102-1', 'Business Mathematics and Statistics', 'Dr. Bhagyalakshmi', NULL, false),
  ('1BcomIBA', 'FRI', 'M2', 'BIBA103-1', 'Busi.Economics', 'Dr. Deon Babloo Thomas', NULL, false),
  ('1BcomIBA', 'SAT', 'M1', 'BIBA103-1', 'Busi.Economics', 'Dr. Deon Babloo Thomas', NULL, false),
  ('1BcomIBA', 'SAT', 'M2', 'BIBA101-1', 'Foundations of Accounting', 'Dr. Shruthi Joshi', NULL, false),
  ('1BcomF&A', 'THU', 'M1', 'COC101-1', 'Fundamentals of accounting', 'Dr. Ravi', NULL, false),
  ('1BcomF&A', 'THU', 'P1', 'COC102-1', 'Business economics', NULL, NULL, false),
  ('1BcomF&A', 'THU', 'P3', NULL, 'PECF', NULL, NULL, false),
  ('1BcomF&A', 'FRI', 'M1', 'COC161-1', 'Legal Aspects of Business', 'CS Monika Agarwal', NULL, false),
  ('1BcomF&A', 'FRI', 'M2', 'COC101-1', 'Fundamentals of accounting', 'Dr. Ravi', NULL, false),
  ('1BcomF&A', 'SAT', 'M1', 'COC103-1', 'Business Mathematics and Statistics', 'Dr. Bhagyalakshmi', NULL, false),
  ('1BcomF&A', 'SAT', 'M2', 'COC101-1', 'Fundamentals of accounting', 'Dr. Ravi', NULL, false),
  ('1BcomF&A', 'SAT', 'P1', 'COC102-1', 'Business economics', NULL, NULL, false),
  ('1BcomIAF', 'THU', 'M1', 'BIAF102-1', 'Business Economics', 'Dr. Deon Babloo Thomas', NULL, false),
  ('1BcomIAF', 'THU', 'P1', 'BIAF101-1', 'Financial Accounting', 'Dr. Narasimha Murthy', NULL, false),
  ('1BcomIAF', 'THU', 'P2', 'BIAF102-1', 'Business Economics', NULL, NULL, false),
  ('1BcomIAF', 'THU', 'P3', NULL, 'PECF', NULL, NULL, false),
  ('1BcomIAF', 'FRI', 'M1', 'BIAF102-1', 'Business Economics', 'Dr. Deon Babloo Thomas', NULL, false),
  ('1BcomIAF', 'FRI', 'M2', 'BIAF101-1', 'Financial Accounting', 'Dr. Narasimha Murthy', NULL, false),
  ('1BcomIAF', 'SAT', 'M1', 'BIAF101-1', 'Financial Accounting', 'Dr. Narasimha Murthy', NULL, false),
  ('1BcomIAF', 'SAT', 'P1', 'DPS161B - 1', 'Fundamentals of Risk and Insurance Skilling / Business Communication and Workplace Skills', 'Dr. Shruthi Joshi', 'Theory', false),
  ('1BcomIAF', 'SAT', 'P2', 'BIAF102-1', 'Business Economics', NULL, NULL, false),
  ('3BcomIBA', 'THU', 'M1', 'BIBA202-3', 'Financial Accounting and Reporting – II', 'CA Sangharsh', NULL, false),
  ('3BcomIBA', 'THU', 'M2', 'BIBA202-3', 'Financial Accounting and Reporting – II', 'CA Sangharsh', NULL, false),
  ('3BcomIBA', 'THU', 'P2', 'BIBA261-3', 'Corporate Law', 'Dr. Deon Babloo Thomas', NULL, false),
  ('3BcomIBA', 'FRI', 'M1', 'BIBA302-3', 'Business Finance', 'Dr. Hridhya', NULL, false),
  ('3BcomIBA', 'FRI', 'M2', 'BIBA302-3', 'Business Finance', 'Dr. Hridhya', NULL, false),
  ('3BcomIBA', 'FRI', 'P2', 'BIBA301-3', 'Management Accounting', 'Dr. Ravi', NULL, false),
  ('3BcomIBA', 'SAT', 'M1', 'BIBA303-3', 'Corporate Reporting', 'CA Abhay', NULL, false),
  ('3BcomIBA', 'SAT', 'M2', 'BIBA303-3', 'Corporate Reporting', 'CA Abhay', NULL, false),
  ('3BcomIBA', 'SAT', 'P1', 'BIBA261-3', 'Corporate Law', 'Dr. Deon Babloo Thomas', NULL, false),
  ('3BcomIBA', 'SAT', 'P2', NULL, 'Yoga', NULL, NULL, false),
  ('3BcomF&A(A)', 'THU', 'M1', 'COC202-3', 'Auditing I', 'CA Devansh', NULL, false),
  ('3BcomF&A(A)', 'THU', 'P2', 'COC301-3', 'Management Accounting', 'Dr. Ravi', NULL, false),
  ('3BcomF&A(A)', 'FRI', 'M1', 'COC203-3', 'Financial Management 1', 'Dr. Thirupathi', NULL, false),
  ('3BcomF&A(A)', 'FRI', 'P2', 'COC361- 3', 'Corporate Legal Framework II', 'Dr. Deon Babloo Thomas', NULL, false),
  ('3BcomF&A(A)', 'SAT', 'M1', 'COC202-3', 'Auditing I', 'CA Devansh', NULL, false),
  ('3BcomF&A(A)', 'SAT', 'M2', 'COC202-3', 'Auditing I', 'CA Devansh', NULL, false),
  ('3BcomF&A(A)', 'SAT', 'P2', 'COC301-3', 'Management Accounting', 'Dr. Ravi', NULL, false),
  ('3BcomF&A(B)', 'THU', 'M1', 'COC202-3', 'Auditing 1', 'Dr. Thirupathi', NULL, false),
  ('3BcomF&A(B)', 'THU', 'P1', 'COC361- 3', 'CORPORATE LEGAL FRAMEWORK - II', 'Dr. Deon Babloo Thomas', NULL, false),
  ('3BcomF&A(B)', 'THU', 'P2', 'COC203-3', 'Financial Management', 'Dr. Shruthi Joshi', NULL, false),
  ('3BcomF&A(B)', 'FRI', 'M1', 'COC201-3', 'Financial Accounting and Reporting – II', 'CA Sangharsh', NULL, false),
  ('3BcomF&A(B)', 'FRI', 'M2', 'COC201-3', 'Financial Accounting and Reporting – II', 'CA Sangharsh', NULL, false),
  ('3BcomF&A(B)', 'FRI', 'P2', 'COC202-3', 'Auditing 1', 'Dr. Thirupathi', NULL, false),
  ('3BcomF&A(B)', 'SAT', 'M1', 'COC301-3', 'Management accounting', 'Dr. Kantharaju', NULL, false),
  ('3BcomF&A(B)', 'SAT', 'P1', NULL, 'Yoga Class', NULL, NULL, false),
  ('3BcomF&A(B)', 'SAT', 'P2', 'COC301-3', 'Management accounting', 'Dr. Kantharaju', NULL, false),
  ('3BcomIAF', 'THU', 'M1', 'BIAF204-3', 'Financial Management', 'Dr. Shruthi Joshi', NULL, false),
  ('3BcomIAF', 'THU', 'M2', 'BIAF201-3', 'Cost Accounting', 'Dr. Kantharaju', NULL, false),
  ('3BcomIAF', 'THU', 'P1', NULL, 'PECF/ CAPS', NULL, NULL, false),
  ('3BcomIAF', 'THU', 'P2', 'BIAF202 - 3', 'Financial Reporting', 'Bhoomika Urs ACCA', NULL, false),
  ('3BcomIAF', 'FRI', 'M1', 'BIAF201-3', 'Cost Accounting', 'Dr. Kantharaju', NULL, false),
  ('3BcomIAF', 'FRI', 'M2', 'BIAF204-3', 'Financial Management', 'Dr. Shruthi Joshi', NULL, false),
  ('3BcomIAF', 'FRI', 'P2', 'BIAF203-3', 'Business & Corporate Law', 'Dr. Narasimha Murthy', NULL, false),
  ('3BcomIAF', 'FRI', 'P3', NULL, 'PECF', NULL, NULL, false),
  ('3BcomIAF', 'SAT', 'M1', 'BIAF204-3', 'Financial Management', 'Dr. Shruthi Joshi', NULL, false),
  ('3BcomIAF', 'SAT', 'M2', 'BIAF202 - 3', 'Financial Reporting', 'Bhoomika Urs ACCA', NULL, false),
  ('3BcomIAF', 'SAT', 'P1', 'BIAF203-3', 'Business & Corporate Law', 'Dr. Narasimha Murthy', NULL, false),
  ('3BcomIAF', 'SAT', 'P2', NULL, 'Yoga class', NULL, NULL, false),
  ('5BcomF&A(A)', 'THU', 'M1', 'COC301-5', 'Strategic Cost Management', 'Bhoomika Urs ACCA', NULL, false),
  ('5BcomF&A(A)', 'THU', 'M2', 'DPS401-5', 'Research Methodology', 'Dr. Thirupathi', NULL, false),
  ('5BcomF&A(A)', 'THU', 'P2', 'DPS401-5', 'Research Methodology', 'Dr. Thirupathi', NULL, false),
  ('5BcomF&A(A)', 'FRI', 'M1', 'DPS303-5A/ DPS303-5B', 'Corporate reporting/ IAPM', 'CA Abhay / Dr. Diliphan', NULL, true),
  ('5BcomF&A(A)', 'FRI', 'M2', 'DPS303-5A/ DPS303-5B', 'Corporate reporting/ IAPM', 'CA Abhay / Dr. Diliphan', NULL, true),
  ('5BcomF&A(A)', 'SAT', 'M1', 'DPS401-5', 'Research Methodology', 'Dr. Thirupathi', NULL, false),
  ('5BcomF&A(A)', 'SAT', 'M2', NULL, 'Industry Practicum', 'Dr. Kantharaju', NULL, false),
  ('5BcomF&A(A)', 'SAT', 'P1', 'COC301-5', 'Strategic Cost Management', 'Bhoomika Urs ACCA', NULL, false),
  ('5BcomF&A(B)', 'THU', 'M1', 'COC301-5', 'Strategic Cost Management', 'CA Rejo', NULL, false),
  ('5BcomF&A(B)', 'THU', 'M2', 'COC301-5', 'Strategic Cost Management', 'CA Rejo', NULL, false),
  ('5BcomF&A(B)', 'FRI', 'M1', 'DPS303-5A/ DPS303-5B', 'Corporate reporting/ IAPM', 'CA Abhay / Dr. Diliphan', NULL, true),
  ('5BcomF&A(B)', 'FRI', 'M2', 'DPS303-5A/ DPS303-5B', 'Corporate reporting/ IAPM', 'CA Abhay / Dr. Diliphan', NULL, true),
  ('5BcomF&A(B)', 'FRI', 'P1', 'COC302-5', 'Entrepreneurship and Start Up Management', 'Dr. Diliphan', NULL, false),
  ('5BcomF&A(B)', 'SAT', 'M1', 'DPS401-5', 'Research Methodology', 'Dr. Hridhya', NULL, false),
  ('5BcomF&A(B)', 'SAT', 'M2', 'COC301-5', 'Strategic Cost Management', 'CA Rejo', NULL, false),
  ('5BcomF&A(B)', 'SAT', 'P1', 'COC301-5', 'Strategic Cost Management 2', 'CA Rejo', NULL, false),
  ('5BcomIAF', 'THU', 'M1', 'BIAF303B-5/ DPS303A-5', 'Entrepreneurial Venture Planning and Communication Strategy / Investment Analysis and Portfolio Management', 'Prof. Bharath / Dr. Diliphan', NULL, true),
  ('5BcomIAF', 'THU', 'M2', 'BIAF303B-5/ DPS303A-5', 'Entrepreneurial Venture Planning and Communication Strategy / Investment Analysis and Portfolio Management', 'Prof. Bharath / Dr. Diliphan', NULL, true),
  ('5BcomIAF', 'THU', 'P2', 'BIAF303-5', 'Strategic Business Management', 'Dr. Narasimha Murthy', NULL, false),
  ('5BcomIAF', 'FRI', 'M1', 'BIAF303-5', 'Strategic Business Management', 'Dr. Narasimha Murthy', NULL, false),
  ('5BcomIAF', 'FRI', 'M2', 'BIAF301-5', 'Corporate Reporting', 'Bhoomika Urs ACCA', NULL, false),
  ('5BcomIAF', 'FRI', 'P2', 'BIAF301-5', 'Corporate Reporting', 'Bhoomika Urs ACCA', NULL, false),
  ('5BcomIAF', 'SAT', 'M1', 'DPS481-5', 'Industry Practicum', 'Bhoomika Urs ACCA', NULL, false),
  ('5BcomIAF', 'SAT', 'P1', 'BIAF302-5', 'Corporate Governance, Risk & Ethics', 'CS Monika Agarwal', NULL, false),
  ('7BcomF&A', 'THU', 'M1', 'COC404B-7/ DPS404A-7', 'INTERNATIONAL TAXATION & TRANSFER PRICING / Project appraisal', 'CA Sarthak / CS Monika Agarwal', NULL, true),
  ('7BcomF&A', 'THU', 'M2', 'COC404B-7/ DPS404A-7', 'INTERNATIONAL TAXATION & TRANSFER PRICING / Project appraisal', 'CA Sarthak / CS Monika Agarwal', NULL, true),
  ('7BcomF&A', 'THU', 'P1', 'DPS401-7', 'International Business', 'Dr. Kantharaju', NULL, false),
  ('7BcomF&A', 'FRI', 'M1', NULL, 'Work Integrated Learning', 'Dr. Shruthi Joshi', NULL, false),
  ('7BcomF&A', 'FRI', 'P1', 'DPS401-7', 'International Business', 'Dr. Kantharaju', NULL, false),
  ('7BcomF&A', 'SAT', 'M1', 'COC404B-7/ DPS404A-7', 'INTERNATIONAL TAXATION & TRANSFER PRICING / Project appraisal', 'CA Sarthak / CS Monika Agarwal', NULL, true),
  ('7BcomF&A', 'SAT', 'M2', 'COC404B-7/ DPS404A-7', 'INTERNATIONAL TAXATION & TRANSFER PRICING / Project appraisal', 'CA Sarthak / CS Monika Agarwal', NULL, true)
  ON CONFLICT (class_name, day, period_name) DO UPDATE SET
    course_code   = EXCLUDED.course_code,
    course_name   = EXCLUDED.course_name,
    faculty_name  = EXCLUDED.faculty_name,
    batch_details = EXCLUDED.batch_details,
    is_elective   = EXCLUDED.is_elective,
    updated_at    = now();
$func$;

GRANT EXECUTE ON FUNCTION reset_timetable_slots() TO anon, authenticated;
